services:

  backend:
    build: .
    container_name: cybersentinel-backend

    ports:
      - "8000:8000"

    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: cybersentinel-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: